### ISSUE TITLE
Exception raised on opening

### ISSUE THREAD

**Issue by LebedevAntony** [atom/fuzzy-finder#100]
I've installed plugin 'grunt-runner' and after that fuzzy-finder is not able to get list of files in project.
When I press Ctrl + P i get following error:

module.js:330
    throw err;
          ^
Cannot find module 'atom' module.js:330
    throw err;
          ^
Error: Cannot find module 'atom'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (...\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\fuzzy-finder\lib\load-paths-handler.js:12:19)
    at Object.<anonymous> (...\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\fuzzy-finder\lib\load-paths-handler.js:177:4)
    at Module._compile (module.js:452:26)
    at Object.Module._extensions..js (module.js:470:10)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)...\AppData\Local\atom\app-0.196.0\resources\app.asar\src\task.js:55 (anonymous function)...\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\emissary\lib\emitter.…:155 (anonymous function)...\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\emissary\lib\emitter.…:154 module.exports.Emitter.emitSlow...\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\emissary\lib\emitter.…:107 module.exports.Emitter.emitC...\AppData\Local\atom\app-0.196.0\resources\app.asar\src\task.js:81 (anonymous function)events.js:87 emitTwoevents.js:169 emitchild_process.js:306 handleMessagechild_process.js:334 channel.onread

and

Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (...\AppData\Local\atom\app-0.196.0\resources\app.asar\src\task-bootstrap.js:82:23)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:169:7)
    at handleMessage (child_process.js:306:10)
    at Pipe.channel.onread (child_process.js:334:11)...\AppData\Local\atom\app-0.196.0\resources\app.asar\src\task.js:55 (anonymous function)...\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\emissary\lib\emitter.…:155 (anonymous function)...\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\emissary\lib\emitter.…:154 module.exports.Emitter.emitSlow...\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\emissary\lib\emitter.…:107 module.exports.Emitter.emit...\AppData\Local\atom\app-0.196.0\resources\app.asar\src\task.js:81 (anonymous function)events.js:87 emitTwoevents.js:169 emitchild_process.js:306 handleMessagechild_process.js:334 channel.onread    

Is it a problem of fuzzy-finder or grunt-runner?

**Comment by LebedevAntony** [comment]
@izuzak Hm...your assumption is correct. It's not reproduced in safe mode. Looks like the problem is in grunt-runner.

**Comment by sirianni** [comment]
I'm receiving the exact same error from fuzzy-finder, but I don't have grunt-runner installed.  Any hints as to how might I go about determining which particular package might be causing this error (other than trial and error)?
