### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by aiboy** [atom/fuzzy-finder#110]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v0.87.0

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:178

TypeError: Arguments to path.join must be strings
  at f (path.js:178:13)
  at Object.filter (native)
  at Object.win32.join (path.js:183:38)
  at GitStatusView.module.exports.GitStatusView.populate (C:\Users\Oleksii.Okhrymenko\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\fuzzy-finder\lib\git-status-view.js:50:27)
  at GitStatusView.module.exports.GitStatusView.toggle (C:\Users\Oleksii.Okhrymenko\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\fuzzy-finder\lib\git-status-view.js:26:14)
  at atom-workspace.atom.commands.add.fuzzy-finder:toggle-git-status-finder (C:\Users\Oleksii.Okhrymenko\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\fuzzy-finder\lib\main.js:34:48)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Oleksii.Okhrymenko\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (C:\Users\Oleksii.Okhrymenko\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Oleksii.Okhrymenko\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:156:19)
  at EventEmitter.<anonymous> (C:\Users\Oleksii.Okhrymenko\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -4:15.7.0 fuzzy-finder:toggle-file-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
 33x -4:05.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:43.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:43 core:move-up (atom-text-editor.editor.mini.is-focused)
     -3:40.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:33.9.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  4x -3:28.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  4x -3:26.3.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  4x -3:25.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
 17x -3:23.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:16.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.8.0 fuzzy-finder:toggle-git-status-finder (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
minimap, v4.10.0
minimap-git-diff, v4.1.3
svn, v0.0.6

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Thanks for the report, @aiboy -- can you reliably reproduce this? Does this happen for all projects or only some?

**Comment by aiboy** [comment]
nope, sorry can't reproduce that any more.. looks like a combinations of plugins + project or just specific project configuration.

can't reproduce that anymore, but for me Arguments to path.join must be strings looks like there is extra

[].filter(function(item){ return typeof(item) === "string" }) is required..
