### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/Ismael/Documents/Hard_Disk/Atom.a...

### ISSUE THREAD

**Issue by ismael2395** [atom/fuzzy-finder#131]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v0.87.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/Ismael/Documents/Hard_Disk/Atom.app/Contents/Resources/app.asar'

```
At fs.js:519

Error: ENOENT: no such file or directory, open '/Users/Ismael/Documents/Hard_Disk/Atom.app/Contents/Resources/app.asar'
  at Error (native)
  at fs.openSync (fs.js:544:18)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:402:12)
  at Object.loadFile [as .js] (/Users/Ismael/Documents/Hard_Disk/Atom.app/Contents/Resources/app.asar/src/babel.js:139:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.module.exports.createProjectView (/Users/Ismael/Documents/Hard_Disk/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/main.js:88:23)
  at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (/Users/Ismael/Documents/Hard_Disk/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/main.js:24:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/Ismael/Documents/Hard_Disk/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Users/Ismael/Documents/Hard_Disk/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/Ismael/Documents/Hard_Disk/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/Ismael/Documents/Hard_Disk/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/Ismael/Documents/Hard_Disk/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -0:59.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:57.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:56.5.0 editor:select-line (atom-text-editor.editor.is-focused)
  2x -0:44 core:save (atom-text-editor.editor.is-focused)
     -0:29.3.0 window:decrease-font-size (atom-text-editor.editor.is-focused)
     -0:21.8.0 window:increase-font-size (atom-text-editor.editor.is-focused)
     -0:14.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.3.0 tree-view:toggle-focus (atom-text-editor.editor.is-focused)
  3x -0:03.6.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  7x -0:03.1.0 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:02.1.0 tool-panel:unfocus (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:01.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:00.2.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "*.pyc",
      "*.git",
      "*.pdf",
      "*.DS_Store",
      "*.png"
    ],
    "themes": [
      "one-dark-ui",
      "monokai-shade-src"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by anton-fomin** [comment]
I have the same error. Just switched to a branch where a folder doesn't exist and opened atom.
