### ISSUE TITLE
Uncaught TypeError: Cannot redefine property: .ts

### ISSUE THREAD

**Issue by Hushpar** [atom/fuzzy-finder#135]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.8
**System**: Unknown Windows Version
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v0.88.0

### Stack Trace

Uncaught TypeError: Cannot redefine property: .ts

```
At c:\Users\All\AppData\Local\atom\app-1.0.8\resources\app.asar\src\compile-cache.js:164

TypeError: Cannot redefine property: .ts
    at Function.defineProperty (native)
    at c:\Users\All\AppData\Local\atom\app-1.0.8\resources\app.asar\src\compile-cache.js:164:10
    at Array.forEach (native)
    at Object.<anonymous> (c:\Users\All\AppData\Local\atom\app-1.0.8\resources\app.asar\src\compile-cache.js:161:24)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value (c:\Users\All\AppData\Local\atom\app-1.0.8\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at new Task (c:\Users\All\AppData\Local\atom\app-1.0.8\resources\app.asar\src\task.js:32:26)
    at Function.module.exports.Task.once (c:\Users\All\AppData\Local\atom\app-1.0.8\resources\app.asar\src\task.js:19:14)
    at Object.module.exports.startTask (c:\Users\All\AppData\Local\atom\app-1.0.8\resources\app.asar\node_modules\fuzzy-finder\lib\path-loader.js:15:19)
    at Object.module.exports.startLoadPathsTask (c:\Users\All\AppData\Local\atom\app-1.0.8\resources\app.asar\node_modules\fuzzy-finder\lib\main.js:120:39)
    at c:\Users\All\AppData\Local\atom\app-1.0.8\resources\app.asar\node_modules\fuzzy-finder\lib\main.js:40:24
    at process._tickCallback (node.js:357:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-ruby, v0.1.0
emmet, v2.3.12
file-icon-supplement, v0.8.3
file-icons, v1.6.9

# Dev
No dev packages
```

**Comment by izuzak** [comment]
No need to open the same issue twice, I'm going to close this in favor of https://github.com/atom/atom/issues/8551.
