### ISSUE TITLE
Uncaught Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by xcjs** [atom/fuzzy-finder#195]
[Enter steps to reproduce below:]
1. Had one instance of Atom open.
2. Called atom . from the command line (for a second instance).
3. Pressed Ctrl + P to search for a file, and it crashed.

**Atom Version**: 1.7.1
**System**: Unknown Windows Version [Reporter note: Windows 10 Professional]
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.4
### Stack Trace

Uncaught Error: spawn UNKNOWN

```
At internal/child_process.js:298

Error: spawn UNKNOWN
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:374:9)
    at Object.exports.fork (child_process.js:66:10)
    at new Task (C:\Users\zack.lowery\AppData\Local\atom\app-1.7.1\resources\app.asar\src\task.js:41:40)
    at Function.module.exports.Task.once (C:\Users\zack.lowery\AppData\Local\atom\app-1.7.1\resources\app.asar\src\task.js:17:14)
    at Object.module.exports.startTask (C:\Users\zack.lowery\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\fuzzy-finder\lib\path-loader.js:22:19)
    at Object.module.exports.startLoadPathsTask (C:\Users\zack.lowery\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\fuzzy-finder\lib\main.js:105:39)
    at C:\Users\zack.lowery\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\fuzzy-finder\lib\main.js:25:24
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter",
      "linter-jsonlint",
      "linter-sass-lint",
      "linter-jshint",
      "jshint"
    ],
    "themes": [
      "atom-material-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by pawelsawicz** [comment]
Additional information, for me it occurs only if I open atom via `git-bash`. When I open atom via `powershell` it works fine.

**Comment by xcjs** [comment]
Ah. The git-bash makes sense. I'm starting Atom via Cygwin.

**Comment by jparkerweb** [comment]
same here, starting via git-bash causes the issue.  opening from file context menu works just fine (windows obviously)

**Comment by 50Wliu** [comment]
Can someone please try copying the files [here](https://github.com/atom/atom/tree/master/resources/win) into (I believe the location is) `%localappdata%\atom\bin` and see if the problem is resolved?

@xcjs Just curious...can you paste the output of `systeminfo` here?  Thanks.

**Comment by hotrice** [comment]
I can confirm that by using Windows CMD and Powershell with atom . work normally without error. Whenever I run atom . with git-bash or other bash or terminal it will throw this error.
