### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/home/psingh/atom:'

### ISSUE THREAD

**Issue by Synergist** [atom/fuzzy-finder#196]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Ubuntu 14.04.4
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/psingh/atom:'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/home/psingh/atom:'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at /usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at ProjectView.module.exports.ProjectView.runLoadPathsTask (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:190:46)
    at ProjectView.module.exports.ProjectView.populate (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:111:21)
    at ProjectView.module.exports.ProjectView.toggle (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:87:14)
    at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/main.js:9:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -3:38.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -3:38.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -3:38.2.0 markdown-preview:toggle (a.inline-block)
     -2:40.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -2:38.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:38.3.0 application:open-your-config (atom-text-editor.editor)
     -2:16.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -2:13.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:13.1.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -2:08.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:34.4.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:31.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:17.9.0 pane:split-right (a.icon.icon-settings)
     -0:06.4.0 command-palette:toggle (atom-pane.pane.active)
     -0:05.4.0 pane:close (div.item-views)
     -0:00.6.0 fuzzy-finder:toggle-file-finder (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
minimap, v4.22.1

# Dev
No dev packages
```

**Comment by rossburton** [comment]
I filed #199, the way I can make this happen on demand is to have atom open a project on a network drive and then forcibly disconnect the mount.  Basically every time I open my laptop when I start work, Atom crashes.

**Comment by thedaniel** [comment]
This one's a bit troubling, at least per @rossburton's repro steps, because it seems to boil down to a more general question about "what should Atom do if the entire project disappears from the filesystem?" 

We can't do any actions to a project that we can't access, so all the things in atom that assume the ability to read or stat files won't work. Maybe we can add a concept of a "disabled" project and suspend any interaction with it until the path exists again?

In the short term, we can probably just catch this exception in fuzzy finder and show something in the info area

**Comment by rossburton** [comment]
Don't disable the entire project: if someone has unsaved changes and the
network drive/removable media/whatever suddenly ceases to exist, you'd
still want to save the file somewhere else.

**Comment by kuychaco** [comment]
As of v1.7 we periodically store the editor state in IndexedDB for crash recovery, so unsaved changes are technically saved in Atom's client-side storage. I have not tested this, but I _believe_ that once the network drive is reconnected and an editor is opened with the same project paths the editor should be restored to the state it was in before the crash, including any unsaved buffer changes
