### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Patrycjusz\AppData\Local\atom\...

### ISSUE THREAD

**Issue by hellshelix** [atom/fuzzy-finder#202]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Patrycjusz\AppData\Local\atom\app-1.7.3\atom:'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat 'C:\Users\Patrycjusz\AppData\Local\atom\app-1.7.3\atom:'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at C:\Users\Patrycjusz\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\fuzzy-finder\lib\path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (C:\Users\Patrycjusz\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\fuzzy-finder\lib\path-loader.js:17:46)
    at ProjectView.module.exports.ProjectView.runLoadPathsTask (C:\Users\Patrycjusz\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\fuzzy-finder\lib\project-view.js:190:46)
    at ProjectView.module.exports.ProjectView.populate (C:\Users\Patrycjusz\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\fuzzy-finder\lib\project-view.js:111:21)
    at ProjectView.module.exports.ProjectView.toggle (C:\Users\Patrycjusz\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\fuzzy-finder\lib\project-view.js:87:14)
    at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (C:\Users\Patrycjusz\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\fuzzy-finder\lib\main.js:9:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Patrycjusz\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Patrycjusz\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Patrycjusz\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Patrycjusz\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Patrycjusz\AppData\Local\atom\app-1.7.3\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\Patrycjusz\AppData\Local\atom\app-1.7.3\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:23.5.0 tabs:close-all-tabs (atom-text-editor.editor.is-focused)
     -0:05.7.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
emmet, v2.4.3
keyboard-localization, v1.4.18
linter, v1.11.4
linter-php, v1.2.0
minimap, v4.23.2
pigments, v0.26.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.9.0-beta0 and above.
