### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\USERNAME\AppData\Local\atom\app...

### ISSUE THREAD

**Issue by krynnotaur** [atom/fuzzy-finder#203]
[Enter steps to reproduce below:]

1. ... no files open
2. ... type ctrl-t

**Atom Version**: 1.7.3
**System**: Microsoft Windows 10 Pro Insider Preview (14332.rs1_release.160422-1940)
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\USERNAME\AppData\Local\atom\app-1.7.3\atom:'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat 'C:\Users\USERNAME\AppData\Local\atom\app-1.7.3\atom:'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at C:\Users\USERNAME\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\fuzzy-finder\lib\path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (C:\Users\USERNAME\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\fuzzy-finder\lib\path-loader.js:17:46)
    at ProjectView.module.exports.ProjectView.runLoadPathsTask (C:\Users\USERNAME\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\fuzzy-finder\lib\project-view.js:190:46)
    at ProjectView.module.exports.ProjectView.populate (C:\Users\USERNAME\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\fuzzy-finder\lib\project-view.js:111:21)
    at ProjectView.module.exports.ProjectView.toggle (C:\Users\USERNAME\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\fuzzy-finder\lib\project-view.js:87:14)
    at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (C:\Users\USERNAME\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\fuzzy-finder\lib\main.js:9:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\USERNAME\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\USERNAME\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\USERNAME\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\USERNAME\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\USERNAME\AppData\Local\atom\app-1.7.3\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\USERNAME\AppData\Local\atom\app-1.7.3\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -1:42.9.0 application:add-project-folder (atom-pane.pane.active)
     -0:04.9.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
minimap, v4.23.2
pigments, v0.26.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.9.0-beta0 and above.
