### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/Don/GitHub/islandora_deployments'

### ISSUE THREAD

**Issue by DonRichards** [atom/fuzzy-finder#212]
[Enter steps to reproduce below:]
Not really sure the problem. Isn't effecting anything. Just pops up a message (so far) 
1. Open atom
2. Error

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/Don/GitHub/islandora_deployments'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/Don/GitHub/islandora_deployments'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at /opt/homebrew-cask/Caskroom/atom/1.5.4/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (/opt/homebrew-cask/Caskroom/atom/1.5.4/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at ProjectView.module.exports.ProjectView.runLoadPathsTask (/opt/homebrew-cask/Caskroom/atom/1.5.4/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:190:46)
    at ProjectView.module.exports.ProjectView.populate (/opt/homebrew-cask/Caskroom/atom/1.5.4/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:111:21)
    at ProjectView.module.exports.ProjectView.toggle (/opt/homebrew-cask/Caskroom/atom/1.5.4/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:87:14)
    at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (/opt/homebrew-cask/Caskroom/atom/1.5.4/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/main.js:9:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.5.4/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/1.5.4/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.5.4/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.5.4/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/homebrew-cask/Caskroom/atom/1.5.4/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.5.4/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:05.8.0 application:new-file (input.hidden-input)
     -0:03.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "chester-atom-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v1.3.0
atom-jade, v0.3.0
atom-typescript, v8.9.1
chester-atom-syntax, v0.1.1
docblockr, v0.7.3
linter, v1.11.4
linter-eslint, v7.1.3
swackets, v0.10.0
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This should be fixed by #204 (and will be available in Atom 1.9.0), so closing.
