### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/myProjectsDir/myProject'

### ISSUE THREAD

**Issue by betesh** [atom/fuzzy-finder#213]
### Steps to reproduce:

1. Open atom
2. Add a project
2. delete the project directory

**Atom Version**: 1.7.3
**System**: Ubuntu 14.04.4
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/myProjectsDir/myProject'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/myProjectsDir/myProject'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at /usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at ProjectView.module.exports.ProjectView.runLoadPathsTask (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:190:46)
    at ProjectView.module.exports.ProjectView.populate (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:111:21)
    at ProjectView.module.exports.ProjectView.toggle (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:87:14)
    at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/main.js:9:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:13.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:13.4.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:11.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:11.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:11.1.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:10.8.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:10.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:09.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:08.5.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:07.2.0 core:move-down (atom-text-editor.editor.is-focused)
  8x -0:05.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:04.5.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:04.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:02.7.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:01.8.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:00.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "openEmptyEditorOnStart": false,
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ]
  },
  "fuzzy-finder": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This should be fixed by #204 (and will be available in Atom 1.9.0), so closing.
