### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, realpath 'atom://.atom/config'

### ISSUE THREAD

**Issue by gidway** [atom/fuzzy-finder#220]
1. install atom from (unofficial)arch/repo
2. run atom from command line /usr/bin/atom

**Atom Version**: 1.7.4
**System**: linux 4.5.4-1-ARCH
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, realpath 'atom://.atom/config'

```
At fs.js:1578

Error: ENOENT: no such file or directory, realpath 'atom://.atom/config'
    at Error (native)
    at Object.realpathSync (fs.js:1578:18)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:303:29)
    at /usr/lib/atom/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.startTask (/usr/lib/atom/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at ProjectView.module.exports.ProjectView.runLoadPathsTask (/usr/lib/atom/node_modules/fuzzy-finder/lib/project-view.js:190:46)
    at ProjectView.module.exports.ProjectView.populate (/usr/lib/atom/node_modules/fuzzy-finder/lib/project-view.js:111:21)
    at ProjectView.module.exports.ProjectView.toggle (/usr/lib/atom/node_modules/fuzzy-finder/lib/project-view.js:87:14)
    at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (/usr/lib/atom/node_modules/fuzzy-finder/lib/main.js:9:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:260:29)
    at /usr/lib/atom/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/lib/atom/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/lib/atom/src/window-event-handler.js:3:61)
```

### Commands

```
     -6:08.8.0 core:move-right (atom-text-editor.editor.is-focused.power-mode)
  2x -6:08.6.0 core:select-left (atom-text-editor.editor.is-focused.power-mode)
  2x -6:07.0 core:select-right (atom-text-editor.editor.is-focused.power-mode.mini)
     -6:05.5.0 core:save (atom-text-editor.editor.is-focused.power-mode)
     -6:01.6.0 core:move-up (atom-text-editor.editor.is-focused.power-mode)
     -6:01.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused.power-mode.mini)
     -6:01.2.0 core:move-left (atom-text-editor.editor.is-focused.power-mode)
     -6:00.9.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused.power-mode.mini)
  2x -5:58.4.0 core:save (atom-text-editor.editor.is-focused.power-mode)
  2x -4:51.7.0 tree-view:toggle-focus (div.panels-item)
     -4:48.1.0 pane:show-next-item (ul.list-inline.tab-bar.inset-panel)
     -4:44.4.0 tree-view:toggle-focus (atom-text-editor.editor.power-mode.is-focused)
     -0:00.8.0 fuzzy-finder:toggle-file-finder (div.panels-item)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2
atomic-chrome, v0.3.0
minimap, v4.24.2
pigments, v0.27.1

# Dev
No dev packages
```

**Comment by gidway** [comment]
The problem was after I installed atom(v.1.7.4) from repo Arch Linux
Today atom has been updated to version 1.7.4-2, and has been running correctly.
Verry quick reaction on bugreport :) Thx
