### ISSUE TITLE
Uncaught TypeError: this.childProcess.send is not a function

### ISSUE THREAD

**Issue by asbjornu** [atom/fuzzy-finder#223]
I think this occurred when I checked for plugin updates.

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught TypeError: this.childProcess.send is not a function

```
At /opt/homebrew-cask/Caskroom/atom/1.0.2/Atom.app/Contents/Resources/app.asar/src/task.js:117

TypeError: this.childProcess.send is not a function
    at Task.module.exports.Task.send (/opt/homebrew-cask/Caskroom/atom/1.0.2/Atom.app/Contents/Resources/app.asar/src/task.js:117:27)
    at Task.module.exports.Task.start (/opt/homebrew-cask/Caskroom/atom/1.0.2/Atom.app/Contents/Resources/app.asar/src/task.js:108:12)
    at Function.module.exports.Task.once (/opt/homebrew-cask/Caskroom/atom/1.0.2/Atom.app/Contents/Resources/app.asar/src/task.js:21:18)
    at Object.module.exports.startTask (/opt/homebrew-cask/Caskroom/atom/1.0.2/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:22:19)
    at Object.module.exports.startLoadPathsTask (/opt/homebrew-cask/Caskroom/atom/1.0.2/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/main.js:105:39)
    at /opt/homebrew-cask/Caskroom/atom/1.0.2/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/main.js:25:24
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "atom-sharp",
      "autosave"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by Connormiha** [comment]
Same problem. Atom 1.13.1
