### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/ufuk/Desktop/experimental/instag...

### ISSUE THREAD

**Issue by spekulatif** [atom/fuzzy-finder#228]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.10.5
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/ufuk/Desktop/experimental/instagram-hackhands'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/ufuk/Desktop/experimental/instagram-hackhands'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at ProjectView.module.exports.ProjectView.runLoadPathsTask (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:190:46)
    at ProjectView.module.exports.ProjectView.populate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:111:21)
    at ProjectView.module.exports.ProjectView.toggle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:87:14)
    at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/main.js:9:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -7:19.2.0 application:new-file (atom-text-editor.editor.is-focused)
     -7:13.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -7:11.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -7:11.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -7:11 editor:newline (atom-text-editor.editor.is-focused)
     -7:10.5.0 bracket-matcher:close-tag (atom-text-editor.editor.is-focused)
     -7:09.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -7:08.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -7:08.3.0 core:paste (atom-text-editor.editor.is-focused)
     -6:43.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:43.1.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
     -6:42.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:38.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.9.0-beta0 and above.
