### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/home/rajinwonderland/Documents/novvum-...

### ISSUE THREAD

**Issue by rajinwonderland** [atom/fuzzy-finder#229]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/rajinwonderland/Documents/novvum-site/atom:'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/home/rajinwonderland/Documents/novvum-site/atom:'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at /usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at ProjectView.module.exports.ProjectView.runLoadPathsTask (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:190:46)
    at ProjectView.module.exports.ProjectView.populate (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:111:21)
    at ProjectView.module.exports.ProjectView.toggle (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:87:14)
    at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/main.js:9:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -6:45 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -6:24.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -6:21.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -5:51.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:44.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  8x -5:32.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:30.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 11x -5:23.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -5:20.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:16.6.0 application:open-your-stylesheet (atom-workspace.workspace.scrollbars-visible-always.use-animations.theme-base16-tomorrow-dark-theme.theme-atom-material-ui)
     -0:11 core:undo (atom-text-editor.editor.is-focused)
     -0:00.7.0 fuzzy-finder:toggle-file-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jsx-transform, v0.2.0
atom-material-ui, v1.2.13
atom-react-native-css, v1.1.2
language-babel, v2.29.2
language-javascript-jsx, v0.3.7
react-es6-snippets, v0.3.0
react-native-snippets, v0.3.0
react-snippets, v0.4.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.9.0-beta0 and above.
