### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Administrator\AppData\Local\at...

### ISSUE THREAD

**Issue by SeokKi** [atom/fuzzy-finder#230]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Administrator\AppData\Local\atom\app-1.8.0\atom:'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat 'C:\Users\Administrator\AppData\Local\atom\app-1.8.0\atom:'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fuzzy-finder\lib\path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fuzzy-finder\lib\path-loader.js:17:46)
    at ProjectView.module.exports.ProjectView.runLoadPathsTask (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fuzzy-finder\lib\project-view.js:190:46)
    at ProjectView.module.exports.ProjectView.populate (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fuzzy-finder\lib\project-view.js:111:21)
    at ProjectView.module.exports.ProjectView.toggle (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fuzzy-finder\lib\project-view.js:87:14)
    at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fuzzy-finder\lib\main.js:9:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:01.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
autocomplete-go, v1.1.0
builder-go, v1.0.0
go-config, v1.2.0
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
linter, v1.11.14
navigator-godef, v1.0.3
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.9.0-beta0 and above.
