### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\vbargl\AppData\Local\atom\app-...

### ISSUE THREAD

**Issue by wotf** [atom/fuzzy-finder#232]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Home
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\vbargl\AppData\Local\atom\app-1.8.0\atom:'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat 'C:\Users\vbargl\AppData\Local\atom\app-1.8.0\atom:'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at C:\Users\vbargl\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fuzzy-finder\lib\path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (C:\Users\vbargl\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fuzzy-finder\lib\path-loader.js:17:46)
    at Object.module.exports.startLoadPathsTask (C:\Users\vbargl\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fuzzy-finder\lib\main.js:105:39)
    at C:\Users\vbargl\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fuzzy-finder\lib\main.js:25:24
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

### Commands

```
     -9:40.4.0 core:save (atom-text-editor.editor.is-focused)
     -9:19.7.0 core:save-as (atom-text-editor.editor.is-focused)
     -7:22.6.0 pane:show-next-item (div.panels)
     -7:19.9.0 core:select-page-down (atom-text-editor.editor.mini.is-focused)
  2x -7:19.2.0 editor:select-to-end-of-line (atom-text-editor.editor.mini.is-focused)
     -1:55.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:52.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:47.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:46.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:59.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:56.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:55.7.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -0:07.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:06.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [],
    "themes": [
      "atom-dark-ui",
      "northem-dark-atom-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.9
emmet, v2.4.3
foldingtext-for-atom, v0.9.2
minimap, v4.24.7
northem-dark-atom-syntax, v0.20.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.9.0-beta0 and above.
