### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/nuclide:'

### ISSUE THREAD

**Issue by tara-marchand** [atom/fuzzy-finder#233]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/nuclide:'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/nuclide:'
  at Error (native)
  at fs.lstatSync (fs.js:887:18)
  at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
  at Object.realpathSync (fs.js:1532:21)
  at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
  at Array.map (native)
  at Object.module.exports.startTask (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
  at ProjectView.module.exports.ProjectView.runLoadPathsTask (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:190:46)
  at ProjectView.module.exports.ProjectView.populate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:111:21)
  at ProjectView.module.exports.ProjectView.toggle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:87:14)
  at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/main.js:9:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

```

### Commands

```
  2x -3:26.8.0 core:backspace (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -3:22.6.0 autocomplete-plus:cancel (atom-text-editor.editor.enable-nuclide-find-references.is-focused.autocomplete-active)
  7x -3:22.2.0 core:move-down (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -3:21.3.0 core:move-up (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -3:17.5.0 pane:show-previous-item (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -3:15.9.0 pane:show-next-item (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
  9x -3:14.4.0 core:move-left (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -3:12.8.0 core:move-right (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
  4x -3:12.3.0 core:backspace (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -3:09.3.0 autocomplete-plus:cancel (atom-text-editor.editor.enable-nuclide-find-references.is-focused.autocomplete-active)
 12x -3:09.0 core:move-left (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
 13x -3:06.0 core:select-left (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -3:03.7.0 core:move-left (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
  4x -3:03.4.0 core:select-right (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -2:59.2.0 core:save (atom-text-editor.editor.enable-nuclide-find-references.is-focused.autocomplete-active)
     -0:03.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "metrics",
      "angularjs",
      "omnisharp-atom",
      "atom-backbone",
      "language-apache",
      "language-cshtml",
      "language-freemarker",
      "linter-eslint",
      "exception-reporting",
      "tree-view",
      "react",
      "json-schema",
      "linter-pylint",
      "linter-gjslint"
    ],
    "projectHome": "/Users/taram/Documents/Projects",
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-beautify, v0.29.9
atom-django, v0.3.2
atom-jinja2, v0.5.0
atom-ternjs, v0.14.2
atom-yeoman, v0.3.15
build, v0.64.0
busy, v0.5.0
change-case, v0.6.0
docblockr, v0.7.3
editorconfig, v1.4.1
emmet, v2.4.3
file-icons, v1.7.16
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
javascript-snippets, v1.2.1
language-babel, v2.30.1
language-ini, v1.16.0
language-ocaml, v1.1.2
language-thrift, v1.0.2
linter, v1.11.14
linter-jscs, v4.0.5
linter-sass-lint, v1.6.1
merge-conflicts, v1.4.4
monokai, v0.18.0
nuclide, v0.148.0
open-recent, v5.0.0
project-manager, v2.9.7
sort-lines, v0.14.0
sync-settings, v0.7.2
terminal-plus, v0.14.5
tool-bar, v1.0.0

# Dev
No dev packages
```

**Comment by vtambourine** [comment]
This problem break fuzzy search on remote project.

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.9.0-beta0 and above.

**Comment by vtambourine** [comment]
I am experiencing the same problem at Atom 1.9.0-beta0.

**Comment by 50Wliu** [comment]
@vtambourine Ok, thanks for reporting back.  Does the issue still occur in safe mode (`atom --safe`)?

**Comment by vtambourine** [comment]
@50Wliu no, in safe mode no error of that kind. Error is occurring only if I connected to the remote host via Nuclide package.

**Comment by 50Wliu** [comment]
@vtambourine Can you also report this to Nuclide?  I'm not sure who's at fault here, so I'm going to reopen this issue in the meantime.

**Comment by johnislarry** [comment]
In Nuclide, when there are remote projects, the paths of those projects are actually URIs.  An example of two projects (one local one remote) below:

```
> atom.project.getPaths()
[
"/Users/jonaldislarry/Nuclide",
"nuclide://our.jonaldislarry.sb.facebook.com/data/users/remote-nuclide",
]
```

My guess is that fuzzy-finder is making the assumption that these will just be normal OS paths, and there's some parsing trouble due to that

**Comment by johnislarry** [comment]
It looks like maybe here

https://github.com/atom/fuzzy-finder/blob/master/lib/path-loader.coffee#L12

there should be a filter on the `atom.project.getPaths()` array with some validation function that would exclude these URI-style paths.

**Comment by 50Wliu** [comment]
Thanks for the info @johnislarry.

**Comment by philippotto** [comment]
Any updates?

**Comment by ayc92** [comment]
Bump!

**Comment by vtambourine** [comment]
I'm on Atom 1.16.0 now, and problem still occurs.
On the other hand, problem occurs only when trying to search via `Cmd + P`. Fuzzy search made via Nuclide package on `Cmd + T` works well.

**Comment by osamie** [comment]
Still seeing this on remote projects. Any update?
My versions:
Atom: 1.18.0
Nuclide: 0.232.0
Client OS:Mac Osx
Server OS (optional): Linux

**Comment by mcraeklaura** [comment]
Any updates?
