### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/home/dave/Documents/contracts/Server'

### ISSUE THREAD

**Issue by baash05** [atom/fuzzy-finder#239]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/dave/Documents/contracts/Server'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/home/dave/Documents/contracts/Server'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at /usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at ProjectView.module.exports.ProjectView.runLoadPathsTask (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:190:46)
    at ProjectView.module.exports.ProjectView.populate (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:111:21)
    at ProjectView.module.exports.ProjectView.toggle (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:87:14)
    at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/main.js:9:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -8:27.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -8:26.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -8:26.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:25.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -8:14.8.0 project-find:show (atom-text-editor.editor.is-focused)
     -8:13.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:53 core:backspace (atom-text-editor.editor.is-focused)
     -7:52.2.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -7:51.7.0 core:select-down (atom-text-editor.editor.is-focused)
     -7:50.7.0 core:select-up (atom-text-editor.editor.is-focused)
  2x -7:50.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -7:48 core:save (atom-text-editor.editor.is-focused)
     -0:16 project-find:show (atom-text-editor.editor.is-focused)
     -0:15.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:14 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 fuzzy-finder:toggle-file-finder (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.9.0-beta0 and above.
