### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/PJoshi/Documents/Projects/websit...

### ISSUE THREAD

**Issue by papajo** [atom/fuzzy-finder#240]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/PJoshi/Documents/Projects/website-sample1'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/PJoshi/Documents/Projects/website-sample1'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at ProjectView.module.exports.ProjectView.runLoadPathsTask (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:190:46)
    at ProjectView.module.exports.ProjectView.populate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:111:21)
    at ProjectView.module.exports.ProjectView.toggle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:87:14)
    at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/main.js:9:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
 10x -1:22.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:18.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:18.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:18.5.0 editor:indent (atom-text-editor.editor.is-focused)
  7x -1:18 core:backspace (atom-text-editor.editor.is-focused)
     -1:09.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:07.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:03.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:03.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:02.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:48.6.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:48.6.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:48.6.0 editor:indent (atom-text-editor.editor.is-focused)
 10x -0:47.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:45.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.60
open-in-browsers, v0.0.16

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.9.0-beta0 and up.
