### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/home/ale/Workspace/e-htl'

### ISSUE THREAD

**Issue by alexandreo** [atom/fuzzy-finder#241]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/ale/Workspace/e-htl'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/home/ale/Workspace/e-htl'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at /opt/atom/resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (/opt/atom/resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at ProjectView.module.exports.ProjectView.runLoadPathsTask (/opt/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:190:46)
    at ProjectView.module.exports.ProjectView.populate (/opt/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:111:21)
    at ProjectView.module.exports.ProjectView.toggle (/opt/atom/resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:87:14)
    at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (/opt/atom/resources/app.asar/node_modules/fuzzy-finder/lib/main.js:9:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:15.3.0 editor:indent (atom-text-editor.editor.is-focused)
     -2:14.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:10.6.0 core:copy (atom-text-editor.editor.is-focused)
     -2:09.9.0 core:paste (atom-text-editor.editor.is-focused)
  4x -1:59.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:56.3.0 core:copy (atom-text-editor.editor.is-focused)
     -1:54.4.0 core:paste (atom-text-editor.editor.is-focused)
     -1:53 core:delete (atom-text-editor.editor.is-focused)
  4x -1:52.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:50.4.0 core:copy (atom-text-editor.editor.is-focused)
     -0:49.7.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:49.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:25 core:page-down (atom-text-editor.editor.is-focused)
  2x -0:20.7.0 core:cut (atom-text-editor.editor.is-focused)
  3x -0:19.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:06.1.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
php-integrator-annotations, v1.0.0
php-integrator-autocomplete-plus, v1.0.2
php-integrator-base, v1.0.7
php-integrator-call-tips, v1.0.0
php-integrator-linter, v1.0.1
php-integrator-navigation, v1.0.0
php-integrator-refactoring, v1.0.0
php-integrator-tooltips, v1.0.0
project-manager, v2.9.7

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.9.0-beta0 and above.
