### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\GiSmo\AppData\Local\atom\app-1...

### ISSUE THREAD

**Issue by GSmurf** [atom/fuzzy-finder#243]
setting / install / Remote Edit

and

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\GiSmo\AppData\Local\atom\app-1.8.0\atom:'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat 'C:\Users\GiSmo\AppData\Local\atom\app-1.8.0\atom:'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at C:\Users\GiSmo\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fuzzy-finder\lib\path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (C:\Users\GiSmo\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fuzzy-finder\lib\path-loader.js:17:46)
    at ProjectView.module.exports.ProjectView.runLoadPathsTask (C:\Users\GiSmo\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fuzzy-finder\lib\project-view.js:190:46)
    at ProjectView.module.exports.ProjectView.populate (C:\Users\GiSmo\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fuzzy-finder\lib\project-view.js:111:21)
    at ProjectView.module.exports.ProjectView.toggle (C:\Users\GiSmo\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fuzzy-finder\lib\project-view.js:87:14)
    at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (C:\Users\GiSmo\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\fuzzy-finder\lib\main.js:9:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\GiSmo\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\GiSmo\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\GiSmo\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\GiSmo\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\GiSmo\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\GiSmo\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:59.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.9.0 fuzzy-finder:toggle-file-finder (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
keyboard-localization, v1.4.18
linter, v1.11.14
linter-js-yaml, v1.2.5
remote-edit, v1.8.24
Sublime-Style-Column-Selection, v1.5.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.9.0-beta0 and above.
