### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/<user>/Library/Caches...

### ISSUE THREAD

**Issue by padusumilli** [atom/fuzzy-finder#245]
[Enter steps to reproduce below:]

1. Open a new tab and enter some text
2. Save file

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.6
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/<user>/Library/Caches/com.binarynights.ForkLift2/#3'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/<User>s/Library/Caches/com.binarynights.ForkLift2/#3'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at ProjectView.module.exports.ProjectView.runLoadPathsTask (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:190:46)
    at ProjectView.module.exports.ProjectView.populate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:111:21)
    at ProjectView.module.exports.ProjectView.toggle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:87:14)
    at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/main.js:9:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:01.2.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.power-mode.is-focused)
     -0:00.3.0 application:new-file (atom-text-editor.editor.power-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "language-freemarker"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.0
file-icons, v1.7.17
highlight-selected, v0.11.2
language-generic-config, v1.1.0
language-puppet, v0.19.1
linter, v1.11.14
linter-puppet, v1.0.0
linter-puppet-lint, v0.7.0
merge-conflicts, v1.4.4
minimap, v4.24.7
pretty-json, v1.4.4

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.9.0-beta0 and above.
