### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/<user>/workspace/api'

### ISSUE THREAD

**Issue by Hashfyre** [atom/fuzzy-finder#246]
[Enter steps to reproduce below:]

1. Project `api` was deleted from filesystem
2. However it was not removed as a project folder in atom
3. Fuzzy Finder bugged out as it tried to find files in a path that did not exist in the fs, but was still in atom's project data structure.

**Atom Version**: 1.8.0
**System**: Mac OS X 10.10.4
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/joy/workspace/razorpay/api'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/joy/workspace/razorpay/api'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at /Users/joy/Downloads/Atom 2.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (/Users/joy/Downloads/Atom 2.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at ProjectView.module.exports.ProjectView.runLoadPathsTask (/Users/joy/Downloads/Atom 2.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:190:46)
    at ProjectView.module.exports.ProjectView.populate (/Users/joy/Downloads/Atom 2.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:111:21)
    at ProjectView.module.exports.ProjectView.toggle (/Users/joy/Downloads/Atom 2.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:87:14)
    at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (/Users/joy/Downloads/Atom 2.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/main.js:9:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/joy/Downloads/Atom 2.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/joy/Downloads/Atom 2.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/joy/Downloads/Atom 2.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/joy/Downloads/Atom 2.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/joy/Downloads/Atom 2.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Users/joy/Downloads/Atom 2.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:02.3.0 core:close (atom-text-editor.editor.is-focused)
     -0:01.2.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/home/joy/workspace/personal/github",
    "themes": [
      "one-dark-ui",
      "firewatch-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.19
atom-jinja2, v0.5.0
autocomplete-go, v1.1.0
builder-go, v1.0.0
docblockr, v0.7.3
file-types, v0.5.1
firewatch-syntax, v1.0.1
git-projects, vundefined
go-config, v1.2.1
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
language-docker, v1.1.6
language-dotenv, v1.0.0
language-nginx, v0.6.1
linter, v1.11.3
linter-ansible-linting, v1.1.0
linter-pep8, v1.2.1
navigator-godef, v1.0.3
release-notes, v0.53.0
sync-settings, v0.6.0
tester-go, v1.0.4
tool-bar, v0.1.9
wercker-status, v1.0.6

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.9.0-beta0 and above.
