### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/anno/Themen/Firma/Bahn/Prisma/Pr...

### ISSUE THREAD

**Issue by hoffmaan** [atom/fuzzy-finder#248]
[Enter steps to reproduce below:]

1. Start Atom, while folder 2016.07.Monatsauswertung doesn't exist --> Atom throws this error.
2. Create the Folder --> Atom throws same error, subfolder rfia.2016.05 missing.
3. Create subfolder --> Atom starts without error message.

$folder and $subfolder have existed before, but I didn't need them any more and deleted them. Looks like fuzzy-finder still keeps references and tries to access them.

Does fuzzy-finder cache references and is there a way to delete them?

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.6
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/anno/Themen/Firma/Bahn/Prisma/Prisma.Themen/2016.07.Monatsauswertung'

```
At fs.js:887

Error: ENOENT: no such file or directory, lstat '/Users/anno/Themen/Firma/Bahn/Prisma/Prisma.Themen/2016.07.Monatsauswertung'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at Object.module.exports.startLoadPathsTask (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/main.js:105:39)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/main.js:25:24
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "audioBeep": false,
    "disabledPackages": [
      "whitespace",
      "tree-view-open-files",
      "git-status",
      "red-wavy-underline",
      "spell-check",
      "opened-files",
      "markdown-scroll-sync"
    ],
    "themes": [
      "hudl-kickoff-dark-ui",
      "hudl-kickoff-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atomic-chrome, v0.3.0
browser-plus, v0.0.60
color-picker, v2.1.1
command-executor, v1.4.2
compare-files, v0.6.2
flex-tool-bar, v0.10.2
glowing-cursor, v0.1.1
highlight-line, v0.11.1
highlight-selected, v0.11.2
hudl-kickoff-dark-syntax, v1.6.1
hudl-kickoff-dark-ui, v2.0.0
markdown-preview-opener, v0.1.1
minimap, v4.24.6
minimap-highlight-selected, v4.4.0
open-unsupported-files, v1.0.19
project-manager, v2.9.7
status-bar-clock, v2.0.4
symbols-tree-view, v0.13.2
tabs-to-spaces, v1.0.2
term3, v0.22.1
tool-bar, v0.4.0
tree-view-git-status, v1.0.1
typewriter, v0.3.5

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This has been fixed in Atom 1.9.0-beta0 and above.
