### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Desktop/and minimum hardware '

### ISSUE THREAD

**Issue by RandoSY** [atom/fuzzy-finder#255]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.9
**System**: Ubuntu 15.04
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.3.0
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/rasyoung/Desktop/and minimum hardware '

```
At ELECTRON_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/home/rasyoung/Desktop/and minimum hardware '
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:228:16)
    at Object.realpathSync (fs.js:1528:21)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:303:29)
    at /opt/atom/resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.module.exports.startTask (/opt/atom/resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at Object.module.exports.startLoadPathsTask (/opt/atom/resources/app.asar/node_modules/fuzzy-finder/lib/main.js:119:39)
    at /opt/atom/resources/app.asar/node_modules/fuzzy-finder/lib/main.js:29:24
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
autocomplete-clang, v0.9.4 (inactive)
build, v0.65.0 (inactive)
busy, v0.6.0 (inactive)
language-ini, v1.16.0 (inactive)
linter, v1.11.16 (inactive)
linter-gcc, v0.6.15 (inactive)
platformio-aia, v0.0.5 (inactive)
platformio-ide, v1.4.0 (inactive)
platformio-ide-terminal, v2.1.1 (inactive)
tool-bar, v1.0.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.0 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.0 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (inactive)
notifications, v0.64.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.1 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (inactive)
timecop, v0.33.1 (inactive)
tree-view, v0.208.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (inactive)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (inactive)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.0 (inactive)
language-less, v0.29.3 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (inactive)
language-shellscript, v0.22.3 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.21.1 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
HI @RandoSY, what were you doing when this exception occurred, and can you reproduce the issue in safe mode (`atom --safe`)?  In addition, can you paste the output of `atom --version` here?  Thanks!

**Comment by Rod-O** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.0
**Electron Version**: 1.3.6
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v1.4.0


### Stack Trace

Uncaught Error: ENOENT: no such file or directory, realpath 'K:\'

```
At fs.js:1584

Error: ENOENT: no such file or directory, realpath 'K:\'
    at Error (native)
    at Object.realpathSync (fs.js:1584:18)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:316:29)
    at C:\Users\rod\AppData\Local\atom\app-1.12.0\resources\app.asar\node_modules\fuzzy-finder\lib\path-loader.js:19:21
    at Array.map (native)
    at Object.startTask (C:\Users\rod\AppData\Local\atom\app-1.12.0\resources\app.asar\node_modules\fuzzy-finder\lib\path-loader.js:17:46)
    at Object.startLoadPathsTask (C:\Users\rod\AppData\Local\atom\app-1.12.0\resources\app.asar\node_modules\fuzzy-finder\lib\main.js:119:39)
    at C:\Users\rod\AppData\Local\atom\app-1.12.0\resources\app.asar\node_modules\fuzzy-finder\lib\main.js:29:24
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "goto-definition",
      "navigator-godef",
      "symbols-view",
      "atom-ctags",
      "goto",
      "linter-gcc"
    ],
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (inactive)
atom-ctags, v5.0.0 (inactive)
autocomplete-go, v1.3.0 (inactive)
builder-go, v1.0.1 (inactive)
go-config, v1.2.4 (inactive)
go-debug, v0.1.22 (inactive)
go-get, v2.1.1 (inactive)
go-plus, v4.3.2 (inactive)
godoc, v1.1.1 (inactive)
gofmt, v1.2.0 (inactive)
gometalinter-linter, v1.2.2 (inactive)
gorename, v1.1.0 (inactive)
goto, v1.7.1 (inactive)
goto-definition, v1.1.19 (inactive)
keybinding-cheatsheet, v0.1.1 (inactive)
linter, v1.11.18 (inactive)
linter-clang, v3.4.4 (inactive)
linter-gcc, v0.6.15 (inactive)
minimap, v4.25.6 (inactive)
minimap-find-and-replace, v4.5.1 (inactive)
navigator-go, v1.1.3 (inactive)
navigator-godef, v1.0.4 (inactive)
switch-header-source, v0.20.0 (inactive)
tester-go, v2.0.2 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.4 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.0 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.1 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (inactive)
snippets, v1.0.3 (inactive)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.46.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by Rod-O** [comment]
> atom --version
Atom    : 1.12.0
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0

**Comment by Rod-O** [comment]
I realized this happens only with Atom 1.12.0 and a virtual SSHFS drive I have, it doesn't happen with other kind of drives.

**Comment by SageHarvey** [comment]
I'm seeing the same error as @Rod-O , also with an SSHFS drive.

```
Atom    : 1.12.3
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0
```

**Comment by mbrobbel** [comment]
https://github.com/nodejs/node/issues/8897
