### ISSUE TITLE
Uncaught Error: spawn EPERM

### ISSUE THREAD

**Issue by amenho** [atom/fuzzy-finder#276]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package 1.4.1

### Stack Trace

Uncaught Error: spawn EPERM

```
At internal/child_process.js:313

Error: spawn EPERM
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:392:9)
    at Object.exports.fork (child_process.js:70:10)
    at /app.asar/src/task.js:41:40)
    at Function.module.exports.Task.once (/app.asar/src/task.js:17:14)
    at Object.startTask (/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:22:19)
    at Object.startLoadPathsTask (/app.asar/node_modules/fuzzy-finder/lib/main.js:117:39)
    at /app.asar/node_modules/fuzzy-finder/lib/main.js:31:24
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-runner 2.7.1 
```

**Comment by 50Wliu** [comment]
Hi @amenho, what were you doing when this error occurred?

**Comment by aireaire** [comment]
I've got the same error while reopening project twice.
1. File->Reopent Project-><select recent project A>
2. From the same instance of Atom immediately do the above step for project B
