### ISSUE TITLE
Uncaught TypeError: this.getEmptyMessage is not a function

### ISSUE THREAD

**Issue by hnguyen94** [atom/fuzzy-finder#287]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package 1.5.0

### Stack Trace

Uncaught TypeError: this.getEmptyMessage is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/fuzzy-finder-view.js:58

TypeError: this.getEmptyMessage is not a function
    at View.FuzzyFinderView (/app.asar/node_modules/fuzzy-finder/lib/fuzzy-finder-view.js:58:26)
    at /packages/rails-finder/lib/view.coffee:6:7)
    at Object.getView (/packages/rails-finder/lib/main.coffee:135:14)
    at Object.getPathes (/packages/rails-finder/lib/main.coffee:132:6)
    at /packages/rails-finder/lib/main.coffee:100:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -2:21.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.compact-tab-bar.compact-tree-view.theme-one-dark-syntax.theme-atom-material-ui)
     -1:09.2.0 rails-finder:toggle-view (input.hidden-input)
     -1:07.1.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
aligner 0.22.3 
aligner-ruby 1.5.0 
atom-beautify 0.29.18 
atom-bootstrap3 1.2.12 
atom-bootstrap4 1.4.0 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-pair 2.0.10 
atom-terminal 0.8.0 
atom-ternjs 0.18.2 
auto-indent 0.5.0 
autocomplete-modules 1.6.9 
autocomplete-paths 1.0.5 
autocomplete-ruby 0.2.6 
busy-signal 1.3.0 
capybara-snippets 0.2.0 
cursor-history 0.9.1 
dash 1.7.1 
docblockr 0.9.4 
emmet 2.4.3 
execute-as-ruby 0.2.1 
file-icons 2.1.3 
foldername-tabs 0.2.4 
gemsource 0.3.0 
git-blame 1.0.0 
git-diff-details 1.4.0 
git-history 3.3.0 
git-plus 7.4.0 
highlight-selected 0.13.1 
history-tracker 0.1.0 
intentions 1.1.2 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
jshint 1.8.6 
language-babel 2.57.3 
language-haml 0.24.1 
language-rspec 0.6.1 
language-slim 0.5.0 
lazy-motion 0.7.0 
linter 2.1.2 
linter-coffeelint 1.2.1 
linter-eslint 8.1.5 
linter-htmlhint 1.3.3 
linter-rubocop 2.0.0 
linter-sass-lint 1.7.4 
linter-ui-default 1.2.2 
linter-write-good 0.9.0 
markdown-pdf 1.5.0 
markdown-preview-plus 2.4.9 
markdown-writer 2.6.4 
merge-conflicts 1.4.4 
minimap 4.27.1 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-split-diff 0.3.7 
nerd-treeview 0.4.3 
nuclide 0.217.0 
open-this 0.4.0 
paner 0.4.0 
pdf-view 0.57.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
project-manager 3.3.4 
rails-finder 0.7.0 
rails-latest-migration 1.1.6 
rails-partials 0.9.2 
rails-snippets 2.15.0 
rails-transporter 1.6.5 
react 0.16.2 
recent-files-fuzzy-finder 0.3.1 
relative-numbers 0.7.1 
remember-file-positions 0.2.2 
ror-refactor 0.3.1 
ruby-block 0.3.6 
ruby-block-converter 3.5.0 
ruby-test 1.0.1 
ruby-test-switcher 1.2.3 
script 3.14.1 
sort-lines 0.14.0 
split-diff 1.3.0 
symbol-gen 1.3.1 
sync-settings 0.8.1 
todo-show 1.11.0 
toggle-packages 1.1.0 
vim-mode-plus 0.88.0 
vim-mode-plus-exchange 0.2.1 
vim-mode-plus-move-selected-text 0.9.0 
vim-mode-plus-move-to-symbols 0.2.0 
wordcount 2.10.4 
Zen 0.16.4 
zentabs 0.8.8 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by hnguyen94** [comment]
I used rails-finder for that.
Everytime I use the shortcut for that plugin, it gives me that error

**Comment by rsese** [comment]
Ohh, sorry I missed that in the stack trace.

In that case, the best place to report this error is the [rails-finder](https://github.com/negipo/rails-finder) package. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
