### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, lstat '/\cco-fil-02\userdata\'

### ISSUE THREAD

**Issue by pcmccollum** [atom/fuzzy-finder#289]
[Enter steps to reproduce:]

1. Start computer
2. Open Atom

**Atom**: 1.16.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package 1.5.0

### Stack Trace

Uncaught Error: EPERM: operation not permitted, lstat '\\cco-fil-02\userdata\'

```
At fs.js:982

Error: EPERM: operation not permitted, lstat '\\cco-fil-02\userdata\'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:239:16)
    at start (fs.js:1634:10)
    at Object.realpathSync (fs.js:1622:3)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:316:29)
    at /app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.startTask (/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at Object.startLoadPathsTask (/app.asar/node_modules/fuzzy-finder/lib/main.js:117:39)
    at /app.asar/node_modules/fuzzy-finder/lib/main.js:31:24
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
  6x -1:49.3.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
script 3.14.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?
* do you have permissions on the file or directory mentioned in the error message (`'\cco-fil-02\userdata'`)?

**Comment by pcmccollum** [comment]
- is the error is reproducible?
Yes
- if reproducible, do you see the error in safe mode (atom --safe)?
Yes, also happens then
- do you have permissions on the file or directory mentioned in the error message ('\cco-fil-02\userdata')?
Ah, no I do not have permissions there, but I do for the subdirectory which contains the files I'm accessing:
\\cco-fil-02\userdata\phillip.mccollum\

**Comment by rsese** [comment]
> do you have permissions on the file or directory mentioned in the error message ('\cco-fil-02\userdata')?
> Ah, no I do not have permissions there, but I do for the subdirectory which contains the files I'm accessing:
> \cco-fil-02\userdata\phillip.mccollum\

Hmm, if you adjust the permission of the higher level directory, does that clear things up?

And just to confirm, are you able to work with the files in `\cco-fil-02\userdata\phillip.mccollum\` or do you get the error and can't open/edit them?

**Comment by rsese** [comment]
Oh and also, I'm assuming this is a remote file on a network drive?

**Comment by pcmccollum** [comment]
Hi Robert,

Unfortunately I don't have the ability to adjust permissions on the higher
level directory, so can't confirm that. But yes, this is a network drive
and I am able to read/write files in my assigned subdirectory.

Thanks!
Phillip

**Comment by rsese** [comment]
Glad to hear the error isn't stopping you from working with the files in the directory you do have permissions on, thanks for confirming that :+1:

**Comment by 50Wliu** [comment]
@pcmccollum When you open Atom, what is your root project folder set to?  `\\cco-fil-02\userdata\`, or the subfolder that you have access to?

**Comment by JackHartCNB** [comment]
> [Enter steps to reproduce:]
> 
> 1. Start computer
> 2. Open Atom
> 
> **Atom**: 1.16.0 ia32
> **Electron**: 1.3.13
> **OS**: Microsoft Windows 7 Enterprise
> **Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package 1.5.0
> 
> ### Stack Trace
> Uncaught Error: EPERM: operation not permitted, lstat '\cco-fil-02\userdata'
> 
> ```
> At fs.js:982
> 
> Error: EPERM: operation not permitted, lstat '\\cco-fil-02\userdata\'
>     at Error (native)
>     at fs.lstatSync (fs.js:982:18)
>     at Object.fs.lstatSync (ELECTRON_ASAR.js:239:16)
>     at start (fs.js:1634:10)
>     at Object.realpathSync (fs.js:1622:3)
>     at Object.fs.realpathSync (ELECTRON_ASAR.js:316:29)
>     at /app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
>     at Array.map (native)
>     at Object.startTask (/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
>     at Object.startLoadPathsTask (/app.asar/node_modules/fuzzy-finder/lib/main.js:117:39)
>     at /app.asar/node_modules/fuzzy-finder/lib/main.js:31:24
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
> ```
> ### Commands
> ```
>   6x -1:49.3.0 core:move-left (input.hidden-input)
> ```
> ### Non-Core Packages
> ```
> script 3.14.1 
> ```

Hi folks.  The way this exception happened in my case was that my windows box had it's home directory and common directories mapped to the wrong server (not my C;\ drive but what Documents and other common directories were mapped to).  Yesterday morning the server that my Documents et al were mapped to was unavailable and I was unable to access any of my files.  One of the sys admins realized that my home directory and common directories were incorrectly mapped and they re-mapped it to the correct drive.  This was after atom had accessed all these files where they had originally been, with the incorrect drive mappings.  When my home and common directories were re-mapped to the correct drive this error started happening.   It appears that atom was maybe holding on to the original mapping?  I'm not sure, but hope that helps.  Thanks for the awesome editor!
