### ISSUE TITLE
Uncaught TypeError: Invalid Point: (NaN, 0)

### ISSUE THREAD

**Issue by yairchu** [atom/fuzzy-finder#299]
I think that I just opened a file when this exception was raised. Hope this helps..

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package 1.5.6

### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, 0)

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (NaN, 0)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/point.js:63:1)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1083:1)
    at DisplayLayer.translateBufferPosition (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:276:1)
    at TextEditor.module.exports.TextEditor.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1652:1)
    at TextEditor.module.exports.TextEditor.scrollToBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3181:1)
    at ProjectView.moveToLine (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/fuzzy-finder-view.js:312:1)
    at ProjectView.confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/fuzzy-finder-view.js:256:1)
    at Object.didConfirmEmptySelection (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/fuzzy-finder-view.js:93:1)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:317:1)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:81:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -5:26.5.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -5:25.7.0 core:confirm (input.hidden-input)
     -5:25.1.0 editor:move-to-first-character-of-line (input.hidden-input)
  2x -5:22.4.0 core:move-right (input.hidden-input)
  5x -5:22 editor:select-to-beginning-of-word (input.hidden-input)
  3x -5:20.9.0 core:select-left (input.hidden-input)
     -5:20 core:backspace (input.hidden-input)
     -5:19.7.0 core:save (input.hidden-input)
     -5:16 core:move-to-top (input.hidden-input)
     -5:15.8.0 editor:move-to-first-character-of-line (input.hidden-input)
  5x -0:19.1.0 core:close (input.hidden-input)
     -0:17.8.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.ide-haskell)
  2x -0:16.2.0 core:backspace (input.hidden-input)
     -0:15.1.0 core:confirm (input.hidden-input)
     -0:14.7.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:14 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
atom-shell-commands 1.5.0 
autocomplete-haskell 0.7.2 
git-diff-details 1.4.0 
haskell-ghc-mod 1.19.9 
highlight-selected 0.13.1 
hover-tooltips-hdevtools 0.10.0 
ide-haskell 1.9.6 
incsearch 0.3.4 
language-haskell 1.12.1 
language-svg 0.9.2 
line-diff-details 1.8.0 
linter-hdevtools 1.10.0 
svg-preview 0.11.0 
```

**Comment by rsese** [comment]
Thanks for the report!  It sounds like it's not but just to confirm, is the error reproducible?  And if so, can you reproduce in safe mode (atom --safe)?

**Comment by yairchu** [comment]
Unfortunately I have no idea how to reproduce it..

**Comment by rsese** [comment]
No problem, thanks for confirming - we'll go ahead and close for now since we don't have repro steps, but if you can reproduce in the future, definitely let us know :v:

**Comment by vincentonderwaater** [comment]
Steps to reproduce (on 1.18.0):
`cmd-T`
Type `::`
*_CRASH_*
