### ISSUE TITLE
Project is empty in a non-empty project

### ISSUE THREAD

**Issue by dafabulousteach** [atom/fuzzy-finder#309]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    *  [X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [X] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Fuzzy Finder reports that Project is empty in a non-empty project

### Steps to Reproduce

1. cmd + p
2. Wait for project to be indexed
3. Fuzzy finder reports empty project
4. Close project
5. Open project
6. Type cmd +p
7. Files are populated

**Expected behavior:** Typing cmd + P + filename results in a list of matching file names 

**Actual behavior:** Fuzzy Finder reports that Project is Empty

**Reproduces how often:** 50%

### Versions
Atom - 1.18.0
OS - macOS Sierra v 10.12.6
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.11
git 2.7.0

### Additional Information
I have have both selected and unselected Exclude VCS Ignored Paths in my Core Settings per suggested

**Comment by fredwu** [comment]
I'm having the same issues lately. Had to close and re-open my projects too to get around this.

**Comment by pbgc** [comment]
I have exactly this problem!

**Comment by pbgc** [comment]
When this happens I have these errors on the console:

Cannot find module 'atom' Error: Cannot find module 'atom'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pbeck/.atom/packages/pigments/lib/tasks/load-paths-handler.coffee:4:19)
    at Object.<anonymous> (/Users/pbeck/.atom/packages/pigments/lib/tasks/load-paths-handler.coffee:1:1)
    at Object.<anonymous> (/Users/pbeck/.atom/packages/pigments/lib/tasks/load-paths-handler.coffee:1:1)
    at Module._compile (module.js:571:32)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:234:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:68:17)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:70:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:424:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:544:3

and 

handler is not defined ReferenceError: handler is not defined
    at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:51:20)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by 50Wliu** [comment]
> at Object. (/Users/pbeck/.atom/packages/pigments/lib/tasks/load-paths-handler.coffee:4:19)

Thanks for contributing!

It appears that this is being caused by the [pigments](https://atom.io/packages/pigments) package, not fuzzy-finder itself. It may be that there is still a bug in fuzzy-finder. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by pbgc** [comment]
After concluding that it was not pigments fault, I started to disable all my extensions one by one ... and the one that was causing the problem (at least .. if I disabled it I don't get this problem and the errors in the console when invoking fuzzy-finder) was atom-elixir - https://atom.io/packages/atom-elixir

**Comment by creattico** [comment]
I have a similar issue. I store files and projects on google drive file stream. It has worked until now, but from a few weeks when I try to use fuzzy finder, Project is empty appear at bottom. Any suggestions?

**Comment by mauricioszabo** [comment]
I have the same problem. On console, these errors appear:

```
<embedded>:11 Could not connect to indexedDB Event
t.onerror.t @ <embedded>:11
<embedded>:14 Cannot find module 'atom' Error: Cannot find module 'atom'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/load-paths-handler.js:6:25)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/fuzzy-finder/lib/load-paths-handler.js:143:3)
    at Module._compile (module.js:642:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:235:23)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/task-bootstrap.js:68:17)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/task-bootstrap.js:70:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
(anonymous) @ <embedded>:14
<embedded>:14 handler is not defined ReferenceError: handler is not defined
    at process.<anonymous> (/usr/share/atom/resources/app.asar/src/task-bootstrap.js:51:20)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)```

**Comment by extremepayne** [comment]
Interestingly enough, I have a related problem: My project will report as empty when there are no matches for my search term, but if my search term has matches it displays correctly. Bug persists even when I disable every non-core package. My problem is less annoying (more of a UI error than an actual performance error), but as I thought it might be related, I'm posting it here.

**Comment by saivan** [comment]
I don't know if this is the same issue. But upon updating atom, I'm getting the same thing. It seems to be somehow related to the updated fuzzy-finder. I have a few folders in my project, and it insists that my project is empty. Turning off ripgrep seems to fix it

**Comment by rsese** [comment]
Since it sounds specific to ripgrep @saivan, can you leave a comment in https://github.com/atom/fuzzy-finder/issues/379?  If you could also share a minimal example and steps to reproduce, that would be super helpful too.
