### ISSUE TITLE
Flaky test: Timeout in test "toggling when the project has multiple paths socket files on #darwin or #linux does not interfere with ability to load files"

### ISSUE THREAD

**Issue by nathansobo** [atom/fuzzy-finder#386]
```
FuzzyFinder
  file-finder behavior (ripgrep=false, scoringSystem=standard)
    toggling
      when the project has multiple paths
        socket files on #darwin or #linux
          it FuzzyFinder file-finder behavior (ripgrep=false, scoringSystem=standard) toggling when the project has multiple paths socket files on #darwin or #linux does not interfere with ability to load files
            timeout: timed out after 60000 msec waiting for condition     at beforeEach (/Users/vsts/agent/2.150.3/work/1/s/node_modules/fuzzy-finder/spec/fuzzy-finder-spec.js:324:15)
        it FuzzyFinder file-finder behavior (ripgrep=false, scoringSystem=standard) toggling when the project has multiple paths ignores paths that match entries in config.fuzzy-finder.ignoredNames
          TypeError: Attempted to wrap cpus which is already wrapped
            at checkWrappedMethod (/Users/vsts/agent/2.150.3/work/1/s/node_modules/sinon/lib/sinon/util/core.js:81:29)
            at Object.wrapMethod (/Users/vsts/agent/2.150.3/work/1/s/node_modules/sinon/lib/sinon/util/core.js:121:21)
            at Object.stub (/Users/vsts/agent/2.150.3/work/1/s/node_modules/sinon/lib/sinon/stub.js:67:26)
            at beforeEach (/Users/vsts/agent/2.150.3/work/1/s/node_modules/fuzzy-finder/spec/fuzzy-finder-spec.js:119:15)
            at jasmine.Spec.<anonymous> (/Users/vsts/agent/2.150.3/work/1/s/node_modules/fuzzy-finder/spec/async-spec-helpers.js:3:20)
            at jasmine.Spec.args.(anonymous function) (/Users/vsts/agent/2.150.3/work/1/s/out/app/spec/jasmine-test-runner.coffee:90:27)
            at <anonymous>
            --------------
            Error: Stack Trace for original
            at Object.wrapMethod (/Users/vsts/agent/2.150.3/work/1/s/node_modules/sinon/lib/sinon/util/core.js:140:34)
            at Object.stub (/Users/vsts/agent/2.150.3/work/1/s/node_modules/sinon/lib/sinon/stub.js:67:26)
            at beforeEach (/Users/vsts/agent/2.150.3/work/1/s/node_modules/fuzzy-finder/spec/fuzzy-finder-spec.js:119:15)
            at jasmine.Spec.<anonymous> (/Users/vsts/agent/2.150.3/work/1/s/node_modules/fuzzy-finder/spec/async-spec-helpers.js:3:20)
            at jasmine.Spec.args.(anonymous function) (/Users/vsts/agent/2.150.3/work/1/s/out/app/spec/jasmine-test-runner.coffee:90:27)
            at <anonymous>
```

[An example](https://github.visualstudio.com/Atom/_build/results?buildId=40521&view=logs&jobId=a5e52b91-c83f-5429-4a68-c246fc63a4f7&taskId=8b9bff53-2841-58c7-68fc-e30c30330fc3&lineStart=757&lineEnd=757&colStart=1&colEnd=12)

[Another example](https://github.visualstudio.com/Atom/_build/results?buildId=40440&view=logs&jobId=a5e52b91-c83f-5429-4a68-c246fc63a4f7&taskId=8b9bff53-2841-58c7-68fc-e30c30330fc3&lineStart=2843&lineEnd=2867&colStart=1&colEnd=1)

**Comment by nathansobo** [comment]
Another one: https://github.visualstudio.com/Atom/_build/results?buildId=40579&view=logs&jobId=a5e52b91-c83f-5429-4a68-c246fc63a4f7&taskId=8b9bff53-2841-58c7-68fc-e30c30330fc3&lineStart=2846&lineEnd=2848&colStart=1&colEnd=1

**Comment by jasonrudolph** [comment]
Another one: https://github.visualstudio.com/Atom/_build/results?buildId=40675&view=logs&jobId=a5e52b91-c83f-5429-4a68-c246fc63a4f7&taskId=8b9bff53-2841-58c7-68fc-e30c30330fc3&lineStart=2839&lineEnd=2867&colStart=1&colEnd=1
