### ISSUE TITLE
Uncaught Error: /usr/lib/atom/node_modules/@atom/fuzzy-native/build/Release/fuzzy-native.node: un...

### ISSUE THREAD

**Issue by Bodenhaltung** [atom/fuzzy-finder#415]
[Enter steps to reproduce:]

1. Start Fuzzy-Search
2. Error

**Atom**: 1.46.0 x64
**Electron**: 4.2.12
**OS**: "Manjaro Linux"
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package 1.14.1

### Stack Trace

Uncaught Error: /usr/lib/atom/node_modules/@atom/fuzzy-native/build/Release/fuzzy-native.node: undefined symbol: _ZN2v82V818GlobalizeReferenceEPNS_8internal7IsolateEPm

```
At ELECTRON_ASAR.js:160

Error: /usr/lib/atom/node_modules/@atom/fuzzy-native/build/Release/fuzzy-native.node: undefined symbol: _ZN2v82V818GlobalizeReferenceEPNS_8internal7IsolateEPm
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Object.<anonymous> (/usr/lib/atom/node_modules/@atom/fuzzy-native/lib/main.js:1:173)
    at Object.<anonymous> (/usr/lib/atom/node_modules/@atom/fuzzy-native/lib/main.js:3:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Object.<anonymous> (/usr/lib/atom/node_modules/fuzzy-finder/lib/fuzzy-finder-view.js:6:21)
    at Object.<anonymous> (/usr/lib/atom/node_modules/fuzzy-finder/lib/fuzzy-finder-view.js:517:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Object.<anonymous> (/usr/lib/atom/node_modules/fuzzy-finder/lib/project-view.js:4:25)
    at Object.<anonymous> (/usr/lib/atom/node_modules/fuzzy-finder/lib/project-view.js:193:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
```

### Commands

```
     -1:11.7.0 core:cancel (input.hidden-input)
     -1:11.1.0 intentions:highlight (input.hidden-input)
     -1:10.9.0 command-palette:toggle (input.hidden-input)
     -1:10 editor:consolidate-selections (input.hidden-input)
     -1:10 core:cancel (input.hidden-input)
     -1:09.7.0 intentions:highlight (input.hidden-input)
     -1:09.6.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -1:04.0 core:cancel (a.stack-toggle)
  2x -1:01.0 window:toggle-full-screen (input.hidden-input)
     -0:11.9.0 intentions:highlight (input.hidden-input)
  4x -0:11.7.0 core:undo (input.hidden-input)
     -0:04.7.0 core:backspace (input.hidden-input)
     -0:03.8.0 intentions:highlight (input.hidden-input)
     -0:03.6.0 core:save (input.hidden-input)
     -0:02.2.0 intentions:highlight (input.hidden-input)
     -0:02.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
ide-php 0.7.18 
intentions 1.1.5 
language-puppet 0.23.0 
linter 2.3.1 
linter-php 1.6.1 
linter-puppet-lint 0.9.0 
linter-shellcheck 1.6.0 
linter-ui-default 1.8.1 
package-sync 1.1.0 
save-commands 0.6.11 
symbols-tree-view 0.14.0 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by Bodenhaltung** [comment]
The issue on github was generated from atom itself...
