### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by odedharth** [atom/fuzzy-finder#438]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.61.0-nightly2 x64
**Electron**: 11.4.12
**OS**: Unknown macOS version
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package 1.14.3

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:292

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:677:19)
    at Task.module.exports.Task.send (/app.asar/src/task.js:111:27)
    at Task.module.exports.Task.start (/app.asar/src/task.js:102:12)
    at Function.module.exports.Task.once (/app.asar/src/task.js:21:18)
    at Object.startTask (/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:23)
    at Object.startLoadPathsTask (/app.asar/node_modules/fuzzy-finder/lib/main.js:129:37)
    at /app.asar/node_modules/fuzzy-finder/lib/main.js:25:33
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

### Commands

```
```

### Non-Core Packages

```
git-plus 8.7.1 
rails-snippets 2.26.0 
```

**Comment by cdstanford** [comment]
Same issue here. This occured after quitting Atom and then reopening it again -- on reopening I got some errors, so quit and reopened a second time, and this time got the "Uncaught Error: write EPIPE".

### Versions

**Atom**: 1.63.0 x64
**Electron**: 11.5.0
**OS**: macOS Monterey
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package 1.14.3


### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:292

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:677:19)
    at Task.module.exports.Task.send (/app.asar/src/task.js:111:27)
    at Task.module.exports.Task.start (/app.asar/src/task.js:102:12)
    at Function.module.exports.Task.once (/app.asar/src/task.js:21:18)
    at Object.startTask (/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:23)
    at Object.startLoadPathsTask (/app.asar/node_modules/fuzzy-finder/lib/main.js:129:37)
    at /app.asar/node_modules/fuzzy-finder/lib/main.js:25:33
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

### Non-Core Packages

```
atom-file-icons 0.7.1 
language-latex 1.2.0 
language-p4 1.4.0 
latex 0.50.2 
```

**Comment by cdstanford** [comment]
Ah, looks like Atom-related issues will no longer be fixed going forward: https://github.blog/2022-06-08-sunsetting-atom/

Time to use vscode I guess. 😆
