### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by Tedko** [atom/fuzzy-finder#86]
[Enter steps to reproduce below:]
1. ...command + T 
2. ...

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.3
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v0.68.0
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/project-view.js:144

TypeError: Cannot read property 'length' of null
  at ProjectView.module.exports.ProjectView.projectRelativePathsForFilePaths (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/project-view.js:144:57)
  at ProjectView.module.exports.FuzzyFinderView.setItems (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/fuzzy-finder-view.js:251:65)
  at ProjectView.module.exports.ProjectView.populate (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/project-view.js:103:14)
  at ProjectView.module.exports.ProjectView.toggle (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/project-view.js:87:14)
  at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/main.js:18:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```
### Commands

```
  2x -4:29.0 window:install-shell-commands (atom-text-editor.editor.vim-mode.command-mode)
     -1:32.5 pane:show-previous-item (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:17.1 core:move-left (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -1:14.0 vim-mode:delete (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -1:12.2 core:save (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  3x -1:05.8 vim-mode:delete (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -1:01.5 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -1:00.9 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:55.9 vim-mode:delete (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -0:55.2 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:53.7 core:undo (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:51.5 core:save (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:10.9 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:09.5 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:09.5 core:cancel (atom-text-editor.editor.mini)
  3x -0:07.7 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "color-gutter",
      "linter"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-color-highlight, v3.0.8
autocomplete-plus, v2.4.2
color-picker, v1.4.4
file-icons, v1.5.1
language-arm, v0.3.0
language-aspx, v0.2.0
language-x86, v0.1.0
minimap, v4.6.0
open-last-project, v0.3.4
vim-mode, v0.37.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
No further repros.
