### ISSUE TITLE
Broken symlinks log errors

### ISSUE THREAD

**Issue by kevinsawicki** [atom/fuzzy-finder#94]
Fuzzy finder is logging errors for any broken symlinks in the project

```
ENOENT: no such file or directory, stat '/Users/kevin/github/atom/node_modules/fs-plus/node_modules/.bin/rimraf'
    at Error (native)
    at fs.statSync (fs.js:846:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
    at Object.realpathSync (fs.js:1456:12)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:243:29)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/load-paths-handler.js:90:20
    at FSReqWrap.oncomplete (fs.js:77:15)
```

**Comment by kevinsawicki** [comment]
This seems to hang the fuzzy finder and prevent it from ever loading, my seems stuck at:

![screen shot 2015-04-14 at 3 14 36 pm](https://cloud.githubusercontent.com/assets/671378/7148583/02a91e0e-e2b9-11e4-9e5b-ecf70e6289f9.png)
